"""
Nature-style combined table: within-group prediction/error diversity
(Humans vs GenAI; D = 1 − mean pairwise cosine) plus diversity–gain
coefficients γ̂_P / γ̂_E.

Reads existing analysis CSVs; does not re-run resampling or permutation tests.
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

import numpy as np

FORECASTS = Path(__file__).resolve().parent
ROOT = FORECASTS.parent
for p in (ROOT, FORECASTS):
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))

from latex_table_pdf import compile_standalone_table  # noqa: E402

OUT_DIR = FORECASTS / "outputs"
TABLE_STEM = "forecast_diversity_combined_table"

REDUNDANCY_CSV = OUT_DIR / "forecast_error_redundancy_detail.csv"
GAIN_COEF_CSV = OUT_DIR / "diversity_explains_gain_coefs.csv"

TASKS = ("Race", "Gender")
TASK_LABELS = {
    "Race": "Racial inequality",
    "Gender": "Gender inequality",
}
ANALYSES = (
    ("Main Effects", "Main effects"),
    ("Interactions", "Interactions"),
)


def _latex_num(value: float, *, decimals: int = 3) -> str:
    if not np.isfinite(value):
        return "—"
    text = f"{value:.{decimals}f}"
    if text.startswith("-"):
        return f"$-{text[1:]}$"
    return text


def _stars(p: float) -> str:
    if not np.isfinite(p):
        return ""
    if p < 0.001:
        return r"$^{***}$"
    if p < 0.01:
        return r"$^{**}$"
    if p < 0.05:
        return r"$^{*}$"
    return ""


def _latex_p(p: float) -> str:
    if not np.isfinite(p):
        return "—"
    if p < 0.001:
        text = "$<$0.001"
    else:
        text = f"{p:.3f}"
    return f"{text}{_stars(p)}"


def _latex_coef_stars(coef: float, p: float) -> str:
    num = _latex_num(coef)
    stars = _stars(p)
    if num.startswith("$") and num.endswith("$") and stars.startswith("$"):
        return f"${num[1:-1]}{stars[1:]}"
    return f"{num}{stars}"


def _diversity_from_sim(sim: float) -> float:
    """D = 1 − mean pairwise cosine (matches OLS diversity regressor)."""
    if not np.isfinite(sim):
        return float("nan")
    return 1.0 - sim


def load_redundancy(
    path: Path = REDUNDANCY_CSV,
) -> dict[tuple[str, str], dict[str, float]]:
    """Keyed by (analysis, task)."""
    out: dict[tuple[str, str], dict[str, float]] = {}
    with path.open(encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            key = (row["analysis"], row["task"])
            out[key] = {
                k: float(row[k])
                for k in row
                if k not in ("task", "analysis")
            }
    return out


def load_gamma(
    path: Path = GAIN_COEF_CSV,
) -> dict[tuple[str, str, str], dict[str, float]]:
    """Keyed by (diversity_key, analysis, task); diversity term only."""
    out: dict[tuple[str, str, str], dict[str, float]] = {}
    with path.open(encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            if row["term"] != "diversity":
                continue
            key = (row["diversity"], row["analysis"], row["task"])
            out[key] = {
                "coef": float(row["coef"]),
                "se": float(row["se"]),
                "p": float(row["p"]),
            }
    return out


def build_combined_tex(
    redundancy: dict[tuple[str, str], dict[str, float]],
    gamma: dict[tuple[str, str, str], dict[str, float]],
) -> str:
    n_cols = 9  # Task + 4 forecast + 4 error
    body: list[str] = []
    for section_idx, (analysis_key, section_label) in enumerate(ANALYSES):
        if section_idx > 0:
            body.append(r"\midrule")
        body.append(
            rf"\multicolumn{{{n_cols}}}{{@{{}}l}}{{\textit{{{section_label}}}}} \\"
        )
        for task in TASKS:
            red = redundancy[(analysis_key, task)]
            g_f = gamma[("diversity_forecast", analysis_key, task)]
            g_e = gamma[("diversity_error", analysis_key, task)]
            # Group means are diversity D = 1 − similarity (p unchanged).
            body.append(
                f"{TASK_LABELS[task]} & "
                f"{_latex_num(_diversity_from_sim(red['forecast_sim_human']))} & "
                f"{_latex_num(_diversity_from_sim(red['forecast_sim_genai']))} & "
                f"{_latex_p(red['forecast_p'])} & "
                f"{_latex_coef_stars(g_f['coef'], g_f['p'])} & "
                f"{_latex_num(_diversity_from_sim(red['error_sim_human']))} & "
                f"{_latex_num(_diversity_from_sim(red['error_sim_genai']))} & "
                f"{_latex_p(red['error_p'])} & "
                f"{_latex_coef_stars(g_e['coef'], g_e['p'])} \\\\"
            )

    return "\n".join([
        "% Auto-generated by combined_diversity_table.py",
        "",
        r"{\footnotesize",
        r"\setlength{\tabcolsep}{4.5pt}",
        r"\renewcommand{\arraystretch}{1.3}",
        r"\begin{tabular}{@{}l*{8}{c}@{}}",
        r"\toprule",
        r" & \multicolumn{4}{c}{Prediction diversity} "
        r"& \multicolumn{4}{c}{Error diversity} \\",
        r"\cmidrule(lr){2-5}\cmidrule(lr){6-9}",
        r"Task & Humans & GenAI & $P$ & $\hat{\gamma}_{P}$"
        r" & Humans & GenAI & $P$ & $\hat{\gamma}_{E}$ \\",
        r"\midrule",
        *body,
        r"\bottomrule",
        r"\end{tabular}",
        r"}",
        "",
    ])


def write_combined_diversity_table(
    *,
    redundancy_csv: Path = REDUNDANCY_CSV,
    gain_coef_csv: Path = GAIN_COEF_CSV,
    out_dir: Path = OUT_DIR,
) -> Path:
    if not redundancy_csv.is_file():
        raise FileNotFoundError(f"Missing redundancy CSV: {redundancy_csv}")
    if not gain_coef_csv.is_file():
        raise FileNotFoundError(f"Missing gain-coef CSV: {gain_coef_csv}")

    tex = build_combined_tex(
        load_redundancy(redundancy_csv),
        load_gamma(gain_coef_csv),
    )
    return compile_standalone_table(
        out_dir,
        TABLE_STEM,
        tex,
        output_format="pdf+svg",
        crop="standalone",
    )


def main() -> None:
    pdf = write_combined_diversity_table()
    print(f"Saved: {OUT_DIR / f'{TABLE_STEM}.tex'}")
    print(f"Saved: {pdf}")


if __name__ == "__main__":
    main()
